add UserAdvancedView and UserFilterProfile
fractal-academy/reportix pull request #9
Opened 2021-03-10 14:54 UTC by okrdima

2021-03-11 15:16 UTC, sashka2131 commented on src/app/domains/user/components/views/UserAdvancedView/UserAdvancedView.template.js
> +      <Row mt={2} h="between">
fix grid please, to much nesting

2021-03-12 09:25 UTC, aleksandrgolyk requested changes

2021-03-12 09:25 UTC, aleksandrgolyk commented on src/app/domains/Request/components/views/RequestAdvancedView/RequestAdvancedView.js
> +                      {statusMap.map((item, index) => {
Use tag component instead of map

2021-03-12 09:25 UTC, aleksandrgolyk commented on src/app/domains/Request/components/views/RequestAdvancedView/RequestAdvancedView.js
> +                      {statusMap.map((item, index) => {
Same here

2021-03-12 13:02 UTC, aleksandrgolyk approved these changes

2021-03-12 13:03 UTC, merged